on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Drop previous dev release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: dev
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
